import { createSlice, PayloadAction } from "@reduxjs/toolkit";

const initialState = {
  isLoading: false,
  error: null,
};

// Create the slice
const searchFlightsSlice = createSlice({
  name: "searchFlights",
  initialState,
  reducers: {
    // Action to set loading state to true (flight search started)
    searchFlightsStart(state) {
      state.isLoading = true;
      state.error = null;
    },
    // Action to set loading state to false (flight search successful)
    searchFlightsSuccess(state) {
      state.isLoading = false;
      state.error = null;
    },
    // Action to set loading state to false and handle error (flight search failed)
    searchFlightsFailure(state, action) {
      state.isLoading = false;
      state.error = action.payload;
    },
  },
});

// Export actions generated by the slice
export const {
  searchFlightsStart,
  searchFlightsSuccess,
  searchFlightsFailure,
} = searchFlightsSlice.actions;

// Export the reducer
export default searchFlightsSlice.reducer;
