export const returntripDemoData = [
  {
    flightCombination: [
      {
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '09:40',
                dateOfArrival: '301024',
                timeOfArrival: '13:05',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 385,
                segmentTime: '6 hours 25 minutes',
                stopOverTime: '7 hours 15 minutes',
                layOverTime: 435,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DAC',
                  terminal: '',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  ARR_ARP: 'BAH',
                  locationId: 'BAH',
                  terminal: '',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                operatingCarrier: 'Gulf Air',
                marketingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '251',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                electronicTicketing: 'Yes',
                cabinClass: 'I',
                availableSeats: '7',
                fareClass: 'I',
                fareBasis: 'ICSMR1BD',
                techstop: '',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '20:20',
                dateOfArrival: '301024',
                timeOfArrival: '22:35',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 75,
                segmentTime: '1 hour 15 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'BAH',
                  terminal: '',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  ARR_ARP: 'DXB',
                  locationId: 'DXB',
                  terminal: '1',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                operatingCarrier: 'Gulf Air',
                marketingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '512',
              productDetail: {
                equipmentType: '32N',
              },
              addProductDetail: {
                electronicTicketing: 'Yes',
                cabinClass: 'I',
                availableSeats: '7',
                fareClass: 'I',
                fareBasis: 'ICSMR1BD',
                techstop: '',
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '23:35',
                dateOfArrival: '041124',
                timeOfArrival: '23:59',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Mon, 4 Nov 2024',
                journeyTime: 84,
                segmentTime: '1 hour 24 minutes',
                stopOverTime: '10 hours 46 minutes',
                layOverTime: 646,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DXB',
                  terminal: '1',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  ARR_ARP: 'BAH',
                  locationId: 'BAH',
                  terminal: '',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                operatingCarrier: 'Gulf Air',
                marketingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '513',
              productDetail: {
                equipmentType: '32N',
              },
              addProductDetail: {
                electronicTicketing: 'Yes',
                cabinClass: 'I',
                availableSeats: '7',
                fareClass: 'I',
                fareBasis: 'ICSMR1BD',
                techstop: '',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '051124',
                timeOfDeparture: '10:45',
                dateOfArrival: '051124',
                timeOfArrival: '18:45',
                dateOfDepartureString: 'Tue, 5 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 300,
                segmentTime: '5 hours 0 minute',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'BAH',
                  terminal: '',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  ARR_ARP: 'DAC',
                  locationId: 'DAC',
                  terminal: '',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                operatingCarrier: 'Gulf Air',
                marketingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '248',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                electronicTicketing: 'Yes',
                cabinClass: 'I',
                availableSeats: '7',
                fareClass: 'I',
                fareBasis: 'ICSMR1BD',
                techstop: '',
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareSummary: {
      breakdown: {
        ADT: {
          totalFareAmount: 260154,
          totalBaseFareAmount: 223609,
          totalTaxAmount: 36545,
          totalFees: 0,
          fareAmount: 130077,
          baseFareAmount: 111804.5,
          taxAmount: 18272.5,
          Fees: 0,
          paxCount: 2,
          lastTicketDate: '30Oct24',
          refundable: true,
          ChangePenalty: 6598,
          ChangePenaltyUnit: 'Amount',
          CancelPenalty: 8998,
          CancelPenaltyUnit: 'Amount',
        },
        CH: {
          totalFareAmount: 128049,
          totalBaseFareAmount: 111805,
          totalTaxAmount: 16244,
          totalFees: 0,
          fareAmount: 128049,
          baseFareAmount: 111805,
          taxAmount: 16244,
          Fees: 0,
          paxCount: 1,
          lastTicketDate: '30Oct24',
          refundable: true,
          ChangePenalty: 6598,
          ChangePenaltyUnit: 'Amount',
          CancelPenalty: 8998,
          CancelPenaltyUnit: 'Amount',
        },
        INF: {
          totalFareAmount: 13308,
          totalBaseFareAmount: 10043,
          totalTaxAmount: 3265,
          totalFees: 0,
          fareAmount: 13308,
          baseFareAmount: 10043,
          taxAmount: 3265,
          Fees: 0,
          paxCount: 1,
          lastTicketDate: '30Oct24',
          refundable: true,
          ChangePenalty: 6598,
          ChangePenaltyUnit: 'Amount',
          CancelPenalty: 8998,
          CancelPenaltyUnit: 'Amount',
        },
      },
      refundable: true,
      refundPenalty: 0,
      lastTicketDate: '30Oct24',
      totalFareAmount: 401511,
      totalTaxAmount: 56054,
      totalBaseFareAmount: 345457,
      Fees: 0,
      Services: 0,
    },
    baggage: [
      {
        ADT: {
          city: 'DAC - DXB',
          freeAllowance: 2,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          city: 'DAC - DXB',
          freeAllowance: 2,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          city: 'DAC - DXB',
          freeAllowance: 1,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          city: 'DXB - DAC',
          freeAllowance: 2,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          city: 'DXB - DAC',
          freeAllowance: 2,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          city: 'DXB - DAC',
          freeAllowance: 1,
          quantityCode: '',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    index: 0,
    has_domestic: true,
    transitAirport: [
      [
        {
          ARR_ARP: 'BAH',
          locationId: 'BAH',
          terminal: '',
          city: 'Bahrain',
          cityCode: 'BAH',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
      [
        {
          ARR_ARP: 'BAH',
          locationId: 'BAH',
          terminal: '',
          city: 'Bahrain',
          cityCode: 'BAH',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
    ],
    code_share: false,
    segmentWiseLayOverMinutes: [435, 646],
    fareType: 'REGULAR',
    cabinClass: ['I', 'I', 'I', 'I'],
    totalLayoverMinutes: 1081,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [],
    validatingCarrier: 'GF',
    finalFare: 401511,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'DXB',
        toCity: 'Dubai',
        toCityCode: 'DXB',
        segmentTime: '14 hours 55 minutes',
      },
      {
        fromCode: 'DXB',
        fromCity: 'Dubai',
        fromCityCode: 'DXB',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '17 hours 10 minutes',
      },
    ],
    baseIndex: 9,
    journeyTimeFrame: ['afterDawn', 'afterDusk'],
    totalLayoverTime: ['lessThanTenHours', 'lessThanFifteenHours'],
    cabinType: 'business',
    flightNumbers: ['GF-251', 'GF-512', 'GF-513', 'GF-248'],
    totalJourneyTime: 844,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Gulf Air',
      code: 'GF',
    },
  },
  {
    flightCombination: [
      {
        propFlightGrDetail: {
          isLcc: false,
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '09:40',
                dateOfArrival: '301024',
                timeOfArrival: '13:05',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 385,
                segmentTime: '6 hours 25 minutes',
                stopOverTime: '12 hours 15 minutes',
                layOverTime: 735,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: null,
                  locationId: 'DAC',
                  cityCode: 'DAC',
                  city: 'Dhaka',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  terminal: null,
                  locationId: 'BAH',
                  cityCode: 'BAH',
                  city: 'Bahrain',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '251',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                availableSeats: 7,
                cabinClass: 'I',
                airlineCode: 'GF',
                airlineName: 'Gulf Air',
                electronicTicketing: 'Y',
                segmentIndicator: 1,
                inFlightServices: [],
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '311024',
                timeOfDeparture: '01:20',
                dateOfArrival: '311024',
                timeOfArrival: '03:35',
                dateOfDepartureString: 'Thu, 31 Oct 2024',
                dateOfArrivalString: 'Thu, 31 Oct 2024',
                journeyTime: 75,
                segmentTime: '1 hour 15 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: null,
                  locationId: 'BAH',
                  cityCode: 'BAH',
                  city: 'Bahrain',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  terminal: '1',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '500',
              productDetail: {
                equipmentType: '32N',
              },
              addProductDetail: {
                availableSeats: 7,
                cabinClass: 'I',
                airlineCode: 'GF',
                airlineName: 'Gulf Air',
                electronicTicketing: 'Y',
                segmentIndicator: 1,
                inFlightServices: [],
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        propFlightGrDetail: {
          isLcc: false,
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '23:35',
                dateOfArrival: '041124',
                timeOfArrival: '23:59',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Mon, 4 Nov 2024',
                journeyTime: 84,
                segmentTime: '1 hour 24 minutes',
                stopOverTime: '10 hours 46 minutes',
                layOverTime: 646,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: '1',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  terminal: null,
                  locationId: 'BAH',
                  cityCode: 'BAH',
                  city: 'Bahrain',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '513',
              productDetail: {
                equipmentType: '32N',
              },
              addProductDetail: {
                availableSeats: 7,
                cabinClass: 'I',
                airlineCode: 'GF',
                airlineName: 'Gulf Air',
                electronicTicketing: 'Y',
                segmentIndicator: 2,
                inFlightServices: [],
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '051124',
                timeOfDeparture: '10:45',
                dateOfArrival: '051124',
                timeOfArrival: '18:45',
                dateOfDepartureString: 'Tue, 5 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 300,
                segmentTime: '5 hours 0 minute',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: null,
                  locationId: 'BAH',
                  cityCode: 'BAH',
                  city: 'Bahrain',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  terminal: null,
                  locationId: 'DAC',
                  cityCode: 'DAC',
                  city: 'Dhaka',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '248',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                availableSeats: 7,
                cabinClass: 'I',
                airlineCode: 'GF',
                airlineName: 'Gulf Air',
                electronicTicketing: 'Y',
                segmentIndicator: 2,
                inFlightServices: [],
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareInformation: null,
    fareSummary: {
      breakdown: {
        ADT: {
          fareAmount: 155329.41,
          taxAmount: 28728.39,
          baseFareAmount: 126601.02,
          totalFareAmount: 310658.82,
          totalBaseFareAmount: 253202.04,
          totalTaxAmount: 57456.78,
          paxCount: 2,
        },
        INF: {
          fareAmount: 17210.77,
          taxAmount: 5545.68,
          baseFareAmount: 11665.08,
          totalFareAmount: 17210.77,
          totalBaseFareAmount: 11665.08,
          totalTaxAmount: 5545.68,
          paxCount: 1,
        },
        CH: {
          fareAmount: 153137.21,
          taxAmount: 26536.18,
          baseFareAmount: 126601.02,
          totalFareAmount: 153137.21,
          totalBaseFareAmount: 126601.02,
          totalTaxAmount: 26536.18,
          paxCount: 1,
        },
      },
      refundable: false,
      totalFareAmount: 481005.52,
      totalTaxAmount: 89538.64,
      totalBaseFareAmount: 391466.88,
    },
    baggage: [
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: null,
          quantityCode: null,
          unitQualifier: null,
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: null,
          quantityCode: null,
          unitQualifier: null,
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    has_domestic: true,
    transitAirport: [
      [
        {
          terminal: null,
          locationId: 'BAH',
          cityCode: 'BAH',
          city: 'Bahrain',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
      [
        {
          terminal: null,
          locationId: 'BAH',
          cityCode: 'BAH',
          city: 'Bahrain',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
    ],
    code_share: false,
    segmentWiseLayOverMinutes: [735, 646],
    fareType: 'REGULAR',
    cabinClass: ['I', 'I', 'I', 'I'],
    totalLayoverMinutes: 1381,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [],
    validatingCarrier: 'GF',
    finalFare: 481005.52,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'DXB',
        toCity: 'Dubai',
        toCityCode: 'DXB',
        segmentTime: '19 hours 55 minutes',
      },
      {
        fromCode: 'DXB',
        fromCity: 'Dubai',
        fromCityCode: 'DXB',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '17 hours 10 minutes',
      },
    ],
    baseIndex: 21,
    journeyTimeFrame: ['afterDawn', 'afterDusk'],
    totalLayoverTime: ['lessThanFifteenHours', 'lessThanFifteenHours'],
    cabinType: 'business',
    flightNumbers: ['GF-251', 'GF-500', 'GF-513', 'GF-248'],
    totalJourneyTime: 844,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Gulf Air',
      code: 'GF',
    },
  },
  {
    flightCombination: [
      {
        propFlightGrDetail: {
          flightProposal: [
            {
              ref: '3',
            },
            {
              ref: '2830',
              unitQualifier: 'EFT',
            },
            {
              ref: 'GF',
              unitQualifier: 'MCX',
            },
          ],
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '09:40',
                dateOfArrival: '301024',
                timeOfArrival: '13:05',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 385,
                segmentTime: '6 hours 25 minutes',
                stopOverTime: '20 hours 45 minutes',
                layOverTime: 1245,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DAC',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  locationId: 'BAH',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                originalMarketingCarrier: 'GF',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '251',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '7',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '311024',
                timeOfDeparture: '09:50',
                dateOfArrival: '311024',
                timeOfArrival: '12:10',
                dateOfDepartureString: 'Thu, 31 Oct 2024',
                dateOfArrivalString: 'Thu, 31 Oct 2024',
                journeyTime: 80,
                segmentTime: '1 hour 20 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'BAH',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  locationId: 'DXB',
                  terminal: '1',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                originalMarketingCarrier: 'GF',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '504',
              productDetail: {
                equipmentType: 'Airbus A320',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '7',
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        propFlightGrDetail: {
          flightProposal: [
            {
              ref: '1',
            },
            {
              ref: '1710',
              unitQualifier: 'EFT',
            },
            {
              ref: 'GF',
              unitQualifier: 'MCX',
            },
          ],
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '23:35',
                dateOfArrival: '041124',
                timeOfArrival: '23:59',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Mon, 4 Nov 2024',
                journeyTime: 84,
                segmentTime: '1 hour 24 minutes',
                stopOverTime: '10 hours 46 minutes',
                layOverTime: 646,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DXB',
                  terminal: '1',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  locationId: 'BAH',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                originalMarketingCarrier: 'GF',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '513',
              productDetail: {
                equipmentType: '32N',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '7',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '051124',
                timeOfDeparture: '10:45',
                dateOfArrival: '051124',
                timeOfArrival: '18:45',
                dateOfDepartureString: 'Tue, 5 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 300,
                segmentTime: '5 hours 0 minute',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'BAH',
                  city: 'Bahrain',
                  cityCode: 'BAH',
                  countryName: 'Bahrain',
                  airportName: "Bahrain Int'l",
                },
                {
                  locationId: 'DAC',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                marketingCarrier: 'Gulf Air',
                operatingCarrier: 'Gulf Air',
                originalMarketingCarrier: 'GF',
                marketingCarrierCode: 'GF',
                operatingCarrierCode: 'GF',
              },
              flightOrtrainNumber: '248',
              productDetail: {
                equipmentType: 'Boeing 787-9',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '7',
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareSummary: {
      breakdown: {
        ADT: {
          fareAmount: 129948.5,
          taxAmount: 18144,
          baseFareAmount: 111804.5,
          totalBaseFareAmount: 223609,
          totalFareAmount: 259897,
          totalTaxAmount: 36288,
          paxCount: 2,
        },
        CH: {
          fareAmount: 127923,
          taxAmount: 16118,
          baseFareAmount: 111805,
          totalBaseFareAmount: 111805,
          totalFareAmount: 127923,
          totalTaxAmount: 16118,
          paxCount: 1,
        },
        INF: {
          fareAmount: 13295,
          taxAmount: 3252,
          baseFareAmount: 10043,
          totalBaseFareAmount: 10043,
          totalFareAmount: 13295,
          totalTaxAmount: 3252,
          paxCount: 1,
        },
      },
      refundable: true,
      refundPenalty: {
        amountType: 'MT',
        amount: '14998',
        currency: 'BDT',
      },
      totalFareAmount: 401115,
      totalTaxAmount: 55658,
      totalBaseFareAmount: 345457,
      fareDetails: {
        ADT: [
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BD',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BD',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BD',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BD',
            paxRefs: ['1', '2'],
          },
        ],
        CH: [
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDCH',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDCH',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDCH',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDCH',
            paxRefs: ['3'],
          },
        ],
        INF: [
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDIN',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDIN',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDIN',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'I',
            availableSeats: '7',
            fareBasis: 'ICSMR1BDIN',
            paxRefs: ['1I'],
          },
        ],
      },
      marketingCarrier: 'GF',
    },
    baggage: [
      {
        ADT: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 0,
          quantityCode: 'W',
          unitQualifier: 'Kg(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 0,
          quantityCode: 'W',
          unitQualifier: 'Kg(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    recommendationId: '1',
    fareBasisDetails: [
      {
        ADT: 'ICSMR1BD',
        CH: 'ICSMR1BDCH',
        INF: 'ICSMR1BDIN',
      },
      {
        ADT: 'ICSMR1BD',
        CH: 'ICSMR1BDCH',
        INF: 'ICSMR1BDIN',
      },
      {
        ADT: 'ICSMR1BD',
        CH: 'ICSMR1BDCH',
        INF: 'ICSMR1BDIN',
      },
      {
        ADT: 'ICSMR1BD',
        CH: 'ICSMR1BDCH',
        INF: 'ICSMR1BDIN',
      },
    ],
    fareBasisRefs: {
      ICSMR1BD: {
        ST: [1, 2, 3, 4],
        PT: ['1', '2'],
      },
      ICSMR1BDCH: {
        ST: [1, 2, 3, 4],
        PT: ['3'],
      },
      ICSMR1BDIN: {
        ST: [1, 2, 3, 4],
        PT: ['1I'],
      },
    },
    has_domestic: true,
    transitAirport: [
      [
        {
          locationId: 'BAH',
          city: 'Bahrain',
          cityCode: 'BAH',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
      [
        {
          locationId: 'BAH',
          city: 'Bahrain',
          cityCode: 'BAH',
          countryName: 'Bahrain',
          airportName: "Bahrain Int'l",
        },
      ],
    ],
    code_share: false,
    segmentWiseLayOverMinutes: [1245, 646],
    fareType: 'REGULAR',
    cabinClass: ['I', 'I', 'I', 'I'],
    totalLayoverMinutes: 1891,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [],
    validatingCarrier: 'GF',
    finalFare: 401115,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'DXB',
        toCity: 'Dubai',
        toCityCode: 'DXB',
        segmentTime: '1 day 4 hours 30 minutes',
      },
      {
        fromCode: 'DXB',
        fromCity: 'Dubai',
        fromCityCode: 'DXB',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '17 hours 10 minutes',
      },
    ],
    baseIndex: 4,
    journeyTimeFrame: ['afterDawn', 'afterDusk'],
    totalLayoverTime: ['moreThanFifteenHours', 'lessThanFifteenHours'],
    cabinType: 'business',
    flightNumbers: ['GF-251', 'GF-504', 'GF-513', 'GF-248'],
    totalJourneyTime: 849,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Gulf Air',
      code: 'GF',
    },
  },
  {
    flightCombination: [
      {
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '01:00',
                dateOfArrival: '301024',
                timeOfArrival: '04:25',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 325,
                segmentTime: '5 hours 25 minutes',
                stopOverTime: '23 hours 5 minutes',
                layOverTime: 1385,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DAC',
                  terminal: '1',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  locationId: 'DXB',
                  terminal: '3',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '585',
              productDetail: {
                equipmentType: 'Boeing 777-300',
              },
              addProductDetail: {
                ref: 'EK-Isgm1c003ba1275ed',
                cabinClass: 'H',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '311024',
                timeOfDeparture: '03:30',
                dateOfArrival: '311024',
                timeOfArrival: '09:30',
                dateOfDepartureString: 'Thu, 31 Oct 2024',
                dateOfArrivalString: 'Thu, 31 Oct 2024',
                journeyTime: 840,
                segmentTime: '14 hours 0 minute',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DXB',
                  terminal: '3',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  locationId: 'YYZ',
                  terminal: '1',
                  city: 'Toronto',
                  cityCode: 'YTO',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '241',
              productDetail: {
                equipmentType: 'Airbus A380-800',
              },
              addProductDetail: {
                ref: 'EK-Isgm02003ba1275ed',
                cabinClass: 'H',
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '13:55',
                dateOfArrival: '051124',
                timeOfArrival: '11:40',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 765,
                segmentTime: '12 hours 45 minutes',
                stopOverTime: '5 hours 5 minutes',
                layOverTime: 305,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'YYZ',
                  terminal: '1',
                  city: 'Toronto',
                  cityCode: 'YTO',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
                {
                  locationId: 'DXB',
                  terminal: '3',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '242',
              productDetail: {
                equipmentType: 'Airbus A380-800',
              },
              addProductDetail: {
                ref: 'EK-Isgm4c013ba1275ed',
                cabinClass: 'I',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '051124',
                timeOfDeparture: '16:45',
                dateOfArrival: '051124',
                timeOfArrival: '23:00',
                dateOfDepartureString: 'Tue, 5 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 255,
                segmentTime: '4 hours 15 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DXB',
                  terminal: '3',
                  city: 'Dubai',
                  cityCode: 'DXB',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  locationId: 'DAC',
                  terminal: '1',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '584',
              productDetail: {
                equipmentType: 'Boeing 777-300',
              },
              addProductDetail: {
                ref: 'EK-Isgm4d013ba1275ed',
                cabinClass: 'I',
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareSummary: {
      refundable: false,
      totalFareAmount: 2094651,
      totalTaxAmount: 95667,
      totalBaseFareAmount: 1998984,
      breakdown: {
        INF: {
          paxCount: 1,
          fareAmount: 77625,
          baseFareAmount: 70408,
          taxAmount: 7217,
          totalFareAmount: 77625,
          totalBaseFareAmount: 70408,
          totalTaxAmount: 7217,
        },
        CH: {
          paxCount: 1,
          fareAmount: 551909,
          baseFareAmount: 525995,
          taxAmount: 25914,
          totalFareAmount: 551909,
          totalBaseFareAmount: 525995,
          totalTaxAmount: 25914,
        },
        ADT: {
          paxCount: 2,
          fareAmount: 732558.5,
          baseFareAmount: 701290.5,
          taxAmount: 31268,
          totalFareAmount: 1465117,
          totalBaseFareAmount: 1402581,
          totalTaxAmount: 62536,
        },
      },
    },
    baggage: [
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 1,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 1,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    refs: {
      offer: {
        refs: [],
        OfferID: {
          value: 'XC7B2146E-ADBA-4587-8F1F-3:XC7B2146E-ADBA-4587-8F1F-60',
          Owner: 'EK',
          Channel: 'NDC',
        },
        OfferItemIDs: {
          OfferItemID: [
            {
              value:
                'XC7B2146E-ADBA-4587-8F1F-3-1:XC7B2146E-ADBA-4587-8F1F-60-1',
              refs: ['EK-T1.1'],
            },
            {
              value:
                'XC7B2146E-ADBA-4587-8F1F-3-2:XC7B2146E-ADBA-4587-8F1F-60-2',
              refs: ['EK-T3'],
            },
            {
              value:
                'XC7B2146E-ADBA-4587-8F1F-3-3:XC7B2146E-ADBA-4587-8F1F-60-3',
              refs: ['EK-T1', 'EK-T2'],
            },
          ],
        },
      },
      metaData: [],
      travelerRefs: {
        'EK-T1.1': 'INF',
        'EK-T3': 'CH',
        'EK-T1': 'ADT',
        'EK-T2': 'ADT',
      },
      originDestinations: [
        {
          Flight: [
            {
              SegmentKey: 'EK-Isgm1c003ba1275ed',
              Departure: {
                AirportCode: {
                  value: 'DAC',
                },
                Date: '2024-10-30T00:00:00.000',
              },
              Arrival: {
                AirportCode: {
                  value: 'DXB',
                },
              },
              MarketingCarrier: {
                AirlineID: {
                  value: 'EK',
                },
                FlightNumber: {
                  value: '585',
                },
              },
            },
            {
              SegmentKey: 'EK-Isgm02003ba1275ed',
              Departure: {
                AirportCode: {
                  value: 'DXB',
                },
                Date: '2024-10-31T00:00:00.000',
              },
              Arrival: {
                AirportCode: {
                  value: 'YYZ',
                },
              },
              MarketingCarrier: {
                AirlineID: {
                  value: 'EK',
                },
                FlightNumber: {
                  value: '241',
                },
              },
            },
          ],
        },
        {
          Flight: [
            {
              SegmentKey: 'EK-Isgm4c013ba1275ed',
              Departure: {
                AirportCode: {
                  value: 'YYZ',
                },
                Date: '2024-11-04T00:00:00.000',
              },
              Arrival: {
                AirportCode: {
                  value: 'DXB',
                },
              },
              MarketingCarrier: {
                AirlineID: {
                  value: 'EK',
                },
                FlightNumber: {
                  value: '242',
                },
              },
            },
            {
              SegmentKey: 'EK-Isgm4d013ba1275ed',
              Departure: {
                AirportCode: {
                  value: 'DXB',
                },
                Date: '2024-11-05T00:00:00.000',
              },
              Arrival: {
                AirportCode: {
                  value: 'DAC',
                },
              },
              MarketingCarrier: {
                AirlineID: {
                  value: 'EK',
                },
                FlightNumber: {
                  value: '584',
                },
              },
            },
          ],
        },
      ],
    },
    fareRules: {
      INF: {
        fareRules: {
          dateChange: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
          refundPolicy: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
        },
      },
      CH: {
        fareRules: {
          dateChange: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
          refundPolicy: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
        },
      },
      ADT: {
        fareRules: {
          dateChange: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
          refundPolicy: {
            maxPenalty: {
              description: 'Maximum penalty amount',
              value: 0,
              currency: 'BDT',
            },
          },
        },
      },
    },
    fareRulesString: '<h3>INF</h3><h3>CH</h3><h3>ADT</h3>',
    isCorpFare: true,
    has_domestic: true,
    transitAirport: [
      [
        {
          locationId: 'DXB',
          terminal: '3',
          city: 'Dubai',
          cityCode: 'DXB',
          countryName: 'United Arab Emirates',
          airportName: 'Dubai',
        },
      ],
      [
        {
          locationId: 'DXB',
          terminal: '3',
          city: 'Dubai',
          cityCode: 'DXB',
          countryName: 'United Arab Emirates',
          airportName: 'Dubai',
        },
      ],
    ],
    code_share: false,
    segmentWiseLayOverMinutes: [1385, 305],
    fareType: 'REGULAR',
    cabinClass: ['H', 'H', 'I', 'I'],
    totalLayoverMinutes: 1690,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [],
    validatingCarrier: 'EK',
    finalFare: 2094651,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'YYZ',
        toCity: 'Toronto',
        toCityCode: 'YTO',
        segmentTime: '1 day 18 hours 30 minutes',
      },
      {
        fromCode: 'YYZ',
        fromCity: 'Toronto',
        fromCityCode: 'YTO',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '22 hours 5 minutes',
      },
    ],
    baseIndex: 2,
    journeyTimeFrame: ['afterMidnight', 'afterNoon'],
    totalLayoverTime: ['moreThanFifteenHours', 'lessThanTenHours'],
    cabinType: 'business',
    flightNumbers: ['EK-585', 'EK-241', 'EK-242', 'EK-584'],
    totalJourneyTime: 2185,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Emirates',
      code: 'EK',
    },
  },
  {
    flightCombination: [
      {
        propFlightGrDetail: {
          flightProposal: [
            {
              ref: '2',
            },
            {
              ref: '2210',
              unitQualifier: 'EFT',
            },
            {
              ref: 'CX',
              unitQualifier: 'MCX',
            },
          ],
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '01:05',
                dateOfArrival: '301024',
                timeOfArrival: '06:40',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 215,
                segmentTime: '3 hours 35 minutes',
                stopOverTime: '3 hours 45 minutes',
                layOverTime: 225,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'DAC',
                  terminal: '1',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  locationId: 'HKG',
                  terminal: '1',
                  city: 'Hong Kong',
                  cityCode: 'HKG',
                  countryName: 'Hongkong',
                  airportName: "Hong Kong Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Cathay Pacific Airways',
                operatingCarrier: 'Cathay Pacific Airways',
                originalMarketingCarrier: 'CX',
                marketingCarrierCode: 'CX',
                operatingCarrierCode: 'CX',
              },
              flightOrtrainNumber: '662',
              productDetail: {
                equipmentType: 'Airbus A330-300',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '9',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '10:25',
                dateOfArrival: '301024',
                timeOfArrival: '13:15',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 890,
                segmentTime: '14 hours 50 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'HKG',
                  terminal: '1',
                  city: 'Hong Kong',
                  cityCode: 'HKG',
                  countryName: 'Hongkong',
                  airportName: "Hong Kong Int'l",
                },
                {
                  locationId: 'YYZ',
                  terminal: '3',
                  city: 'Toronto',
                  cityCode: 'YTO',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Cathay Pacific Airways',
                operatingCarrier: 'Cathay Pacific Airways',
                originalMarketingCarrier: 'CX',
                marketingCarrierCode: 'CX',
                operatingCarrierCode: 'CX',
              },
              flightOrtrainNumber: '828',
              productDetail: {
                equipmentType: '351',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'I',
                availableSeats: '9',
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        propFlightGrDetail: {
          flightProposal: [
            {
              ref: '3',
            },
            {
              ref: '2300',
              unitQualifier: 'EFT',
            },
            {
              ref: 'CX',
              unitQualifier: 'MCX',
            },
          ],
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '13:55',
                dateOfArrival: '051124',
                timeOfArrival: '18:45',
                dateVariation: '1',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 950,
                segmentTime: '15 hours 50 minutes',
                stopOverTime: '2 hours 40 minutes',
                layOverTime: 160,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'YYZ',
                  terminal: '3',
                  city: 'Toronto',
                  cityCode: 'YTO',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
                {
                  locationId: 'HKG',
                  terminal: '1',
                  city: 'Hong Kong',
                  cityCode: 'HKG',
                  countryName: 'Hongkong',
                  airportName: "Hong Kong Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Cathay Pacific Airways',
                operatingCarrier: 'Cathay Pacific Airways',
                originalMarketingCarrier: 'CX',
                marketingCarrierCode: 'CX',
                operatingCarrierCode: 'CX',
              },
              flightOrtrainNumber: '805',
              productDetail: {
                equipmentType: '351',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'D',
                availableSeats: '4',
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '051124',
                timeOfDeparture: '21:25',
                dateOfArrival: '051124',
                timeOfArrival: '23:55',
                dateOfDepartureString: 'Tue, 5 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 270,
                segmentTime: '4 hours 30 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  locationId: 'HKG',
                  terminal: '1',
                  city: 'Hong Kong',
                  cityCode: 'HKG',
                  countryName: 'Hongkong',
                  airportName: "Hong Kong Int'l",
                },
                {
                  locationId: 'DAC',
                  terminal: '1',
                  city: 'Dhaka',
                  cityCode: 'DAC',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                marketingCarrier: 'Cathay Pacific Airways',
                operatingCarrier: 'Cathay Pacific Airways',
                originalMarketingCarrier: 'CX',
                marketingCarrierCode: 'CX',
                operatingCarrierCode: 'CX',
              },
              flightOrtrainNumber: '667',
              productDetail: {
                equipmentType: 'Airbus A330-300',
              },
              addProductDetail: {
                electronicTicketing: 'Y',
                productDetailQualifier: 'AIP',
                cabinClass: 'D',
                availableSeats: '4',
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareSummary: {
      breakdown: {
        ADT: {
          fareAmount: 760218,
          taxAmount: 35942.5,
          baseFareAmount: 724275.5,
          totalBaseFareAmount: 1448551,
          totalFareAmount: 1520436,
          totalTaxAmount: 71885,
          paxCount: 2,
        },
        CH: {
          fareAmount: 573692,
          taxAmount: 30513,
          baseFareAmount: 543179,
          totalBaseFareAmount: 543179,
          totalFareAmount: 573692,
          totalTaxAmount: 30513,
          paxCount: 1,
        },
        INF: {
          fareAmount: 87016,
          taxAmount: 14600,
          baseFareAmount: 72416,
          totalBaseFareAmount: 72416,
          totalFareAmount: 87016,
          totalTaxAmount: 14600,
          paxCount: 1,
        },
      },
      refundable: true,
      refundPenalty: {
        amountType: 'MT',
        amount: '29995',
        currency: 'BDT',
      },
      totalFareAmount: 2181144,
      totalTaxAmount: 116998,
      totalBaseFareAmount: 2064146,
      fareDetails: {
        ADT: [
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['1', '2'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['1', '2'],
          },
        ],
        CH: [
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['3'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['3'],
          },
        ],
        INF: [
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'I',
            availableSeats: '9',
            fareBasis: 'IK99BDAR',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['1I'],
          },
          {
            cabinClass: 'D',
            availableSeats: '4',
            fareBasis: 'DR99BDAR',
            paxRefs: ['1I'],
          },
        ],
      },
      marketingCarrier: 'CX',
    },
    baggage: [
      {
        ADT: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 0,
          quantityCode: 'W',
          unitQualifier: 'Kg(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: '2',
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: 0,
          quantityCode: 'W',
          unitQualifier: 'Kg(s)',
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    recommendationId: '3',
    fareBasisDetails: [
      {
        ADT: 'IK99BDAR',
        CH: 'IK99BDAR',
        INF: 'IK99BDAR',
      },
      {
        ADT: 'IK99BDAR',
        CH: 'IK99BDAR',
        INF: 'IK99BDAR',
      },
      {
        ADT: 'DR99BDAR',
        CH: 'DR99BDAR',
        INF: 'DR99BDAR',
      },
      {
        ADT: 'DR99BDAR',
        CH: 'DR99BDAR',
        INF: 'DR99BDAR',
      },
    ],
    fareBasisRefs: {
      IK99BDAR: {
        ST: [1, 2],
        PT: ['1', '2', '3', '1I'],
      },
      DR99BDAR: {
        ST: [3, 4],
        PT: ['1', '2', '3', '1I'],
      },
    },
    has_domestic: true,
    transitAirport: [
      [
        {
          locationId: 'HKG',
          terminal: '1',
          city: 'Hong Kong',
          cityCode: 'HKG',
          countryName: 'Hongkong',
          airportName: "Hong Kong Int'l",
        },
      ],
      [
        {
          locationId: 'HKG',
          terminal: '1',
          city: 'Hong Kong',
          cityCode: 'HKG',
          countryName: 'Hongkong',
          airportName: "Hong Kong Int'l",
        },
      ],
    ],
    code_share: false,
    segmentWiseLayOverMinutes: [225, 160],
    fareType: 'REGULAR',
    cabinClass: ['I', 'I', 'D', 'D'],
    totalLayoverMinutes: 385,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [],
    validatingCarrier: 'CX',
    finalFare: 2181144,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'YYZ',
        toCity: 'Toronto',
        toCityCode: 'YTO',
        segmentTime: '22 hours 10 minutes',
      },
      {
        fromCode: 'YYZ',
        fromCity: 'Toronto',
        fromCityCode: 'YTO',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '23 hours 0 minute',
      },
    ],
    baseIndex: 20,
    journeyTimeFrame: ['afterMidnight', 'afterNoon'],
    totalLayoverTime: ['lessThanFiveHours', 'lessThanFiveHours'],
    cabinType: 'business',
    flightNumbers: ['CX-662', 'CX-828', 'CX-805', 'CX-667'],
    totalJourneyTime: 2325,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Cathay Pacific Airways',
      code: 'CX',
    },
  },
  {
    flightCombination: [
      {
        propFlightGrDetail: {
          isLcc: false,
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '301024',
                timeOfDeparture: '09:55',
                dateOfArrival: '301024',
                timeOfArrival: '13:20',
                dateOfDepartureString: 'Wed, 30 Oct 2024',
                dateOfArrivalString: 'Wed, 30 Oct 2024',
                journeyTime: 325,
                segmentTime: '5 hours 25 minutes',
                stopOverTime: '14 hours 10 minutes',
                layOverTime: 850,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: '1',
                  locationId: 'DAC',
                  cityCode: 'DAC',
                  city: 'Dhaka',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
                {
                  terminal: '3',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '583',
              productDetail: {
                equipmentType: 'Boeing 777-300ER Passenger',
              },
              addProductDetail: {
                availableSeats: 0,
                cabinClass: 'H',
                airlineCode: 'EK',
                airlineName: 'Emirates',
                electronicTicketing: 'Y',
                segmentIndicator: 1,
                inFlightServices: null,
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '311024',
                timeOfDeparture: '03:30',
                dateOfArrival: '311024',
                timeOfArrival: '09:30',
                dateOfDepartureString: 'Thu, 31 Oct 2024',
                dateOfArrivalString: 'Thu, 31 Oct 2024',
                journeyTime: 840,
                segmentTime: '14 hours 0 minute',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: '3',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  terminal: '1',
                  locationId: 'YYZ',
                  cityCode: 'YTO',
                  city: 'Toronto',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '241',
              productDetail: {
                equipmentType: 'Airbus A380-800 Passenger',
              },
              addProductDetail: {
                availableSeats: 0,
                cabinClass: 'H',
                airlineCode: 'EK',
                airlineName: 'Emirates',
                electronicTicketing: 'Y',
                segmentIndicator: 1,
                inFlightServices: null,
              },
            },
            technicalStop: [],
          },
        ],
      },
      {
        propFlightGrDetail: {
          isLcc: false,
        },
        flightDetails: [
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '041124',
                timeOfDeparture: '13:55',
                dateOfArrival: '051124',
                timeOfArrival: '11:40',
                dateOfDepartureString: 'Mon, 4 Nov 2024',
                dateOfArrivalString: 'Tue, 5 Nov 2024',
                journeyTime: 765,
                segmentTime: '12 hours 45 minutes',
                stopOverTime: '12 hours 40 minutes',
                layOverTime: 760,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: '1',
                  locationId: 'YYZ',
                  cityCode: 'YTO',
                  city: 'Toronto',
                  countryName: 'Canada',
                  airportName: "Pearson Int'l",
                },
                {
                  terminal: '3',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Emirates',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'EK',
              },
              flightOrtrainNumber: '242',
              productDetail: {
                equipmentType: 'Airbus A380-800 Passenger',
              },
              addProductDetail: {
                availableSeats: 0,
                cabinClass: 'I',
                airlineCode: 'EK',
                airlineName: 'Emirates',
                electronicTicketing: 'Y',
                segmentIndicator: 2,
                inFlightServices: null,
              },
            },
            technicalStop: [],
          },
          {
            flightInformation: {
              productDateTime: {
                dateOfDeparture: '061124',
                timeOfDeparture: '00:20',
                dateOfArrival: '061124',
                timeOfArrival: '07:05',
                dateOfDepartureString: 'Wed, 6 Nov 2024',
                dateOfArrivalString: 'Wed, 6 Nov 2024',
                journeyTime: 285,
                segmentTime: '4 hours 45 minutes',
                stopOverTime: '',
                layOverTime: 0,
                isStopOverAirportChange: false,
              },
              location: [
                {
                  terminal: '2',
                  locationId: 'DXB',
                  cityCode: 'DXB',
                  city: 'Dubai',
                  countryName: 'United Arab Emirates',
                  airportName: 'Dubai',
                },
                {
                  terminal: '1',
                  locationId: 'DAC',
                  cityCode: 'DAC',
                  city: 'Dhaka',
                  countryName: 'Bangladesh',
                  airportName: 'Hazrat Shahjalal International Airport',
                },
              ],
              companyId: {
                marketingCarrier: 'Emirates',
                operatingCarrier: 'Flydubai',
                marketingCarrierCode: 'EK',
                operatingCarrierCode: 'FZ',
              },
              flightOrtrainNumber: '2330',
              productDetail: {
                equipmentType: 'Boeing 737-800 -Winglets- Passenger',
              },
              addProductDetail: {
                availableSeats: 0,
                cabinClass: 'I',
                airlineCode: 'EK',
                airlineName: 'Emirates',
                electronicTicketing: 'Y',
                segmentIndicator: 2,
                inFlightServices: null,
              },
            },
            technicalStop: [],
          },
        ],
      },
    ],
    fareInformation: null,
    fareSummary: {
      breakdown: {
        INF: {
          fareAmount: 93809.08,
          taxAmount: 13525.66,
          baseFareAmount: 80283.42,
          totalFareAmount: 93809.08,
          totalBaseFareAmount: 80283.42,
          totalTaxAmount: 13525.66,
          paxCount: 1,
        },
        CH: {
          fareAmount: 661263.07,
          taxAmount: 62226.3,
          baseFareAmount: 599036.76,
          totalFareAmount: 661263.07,
          totalBaseFareAmount: 599036.76,
          totalTaxAmount: 62226.3,
          paxCount: 1,
        },
        ADT: {
          fareAmount: 877208.69,
          taxAmount: 78493.43,
          baseFareAmount: 798715.26,
          totalFareAmount: 1754417.38,
          totalBaseFareAmount: 1597430.52,
          totalTaxAmount: 156986.86,
          paxCount: 2,
        },
      },
      refundable: false,
      totalFareAmount: 2509488.26,
      totalTaxAmount: 232738.82,
      totalBaseFareAmount: 2276749.44,
    },
    baggage: [
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: null,
          quantityCode: null,
          unitQualifier: null,
          cabinBaggage: '7 Kg(s)',
        },
      },
      {
        ADT: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        CH: {
          freeAllowance: 2,
          quantityCode: 'N',
          unitQualifier: 'PC(s)',
          cabinBaggage: '7 Kg(s)',
        },
        INF: {
          freeAllowance: null,
          quantityCode: null,
          unitQualifier: null,
          cabinBaggage: '7 Kg(s)',
        },
      },
    ],
    has_domestic: true,
    transitAirport: [
      [
        {
          terminal: '3',
          locationId: 'DXB',
          cityCode: 'DXB',
          city: 'Dubai',
          countryName: 'United Arab Emirates',
          airportName: 'Dubai',
        },
      ],
      [
        {
          terminal: '3',
          locationId: 'DXB',
          cityCode: 'DXB',
          city: 'Dubai',
          countryName: 'United Arab Emirates',
          airportName: 'Dubai',
        },
      ],
    ],
    code_share: true,
    segmentWiseLayOverMinutes: [850, 760],
    fareType: 'REGULAR',
    cabinClass: ['H', 'H', 'I', 'I'],
    totalLayoverMinutes: 1610,
    hasSSR: 0,
    updatedFareRequired: false,
    airlineRemarks: [
      'Warning: This is a Codeshare flight and flight disruptions may not allow involuntary changes/refunds**',
    ],
    validatingCarrier: 'EK',
    finalFare: 2509488.26,
    flightSummary: [
      {
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        fromCityCode: 'DAC',
        toCode: 'YYZ',
        toCity: 'Toronto',
        toCityCode: 'YTO',
        segmentTime: '1 day 9 hours 35 minutes',
      },
      {
        fromCode: 'YYZ',
        fromCity: 'Toronto',
        fromCityCode: 'YTO',
        toCode: 'DAC',
        toCity: 'Dhaka',
        toCityCode: 'DAC',
        segmentTime: '1 day 6 hours 10 minutes',
      },
    ],
    baseIndex: 69,
    journeyTimeFrame: ['afterDawn', 'afterNoon'],
    totalLayoverTime: ['lessThanFifteenHours', 'lessThanFifteenHours'],
    cabinType: 'business',
    flightNumbers: ['EK-583', 'EK-241', 'EK-242', 'FZ-2330'],
    totalJourneyTime: 2215,
    stops: ['1', '1'],
    marketingCarrier: {
      name: 'Emirates',
      code: 'EK',
    },
  },
];
